name: Build And Publish Develop

on:
  push:
    branches: [ "develop" ]

permissions:
      contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    name: Publish Develop
    uses: ./.github/workflows/publish-develop.yml
    with: 
      name: ${{ needs.build.outputs.name }}
      version: ${{ needs.build.outputs.version }}
    needs: [build]
    secrets: inherit