name: Build And Publish Release

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    name: Publish Release
    uses: ./.github/workflows/publish.yml
    with: 
      name: ${{ needs.build.outputs.name }}
      version: ${{ needs.build.outputs.version }}