name: Build And Publish Release

on:
  pull_request: # change to push
    branches: [ "develop" ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable/build.yml
    secrets: inherit

  publish:
    name: Publish Release
    uses: ./.github/workflows/reusable/publish.yml
    with: 
      name: ${{ needs.build.outputs.name }}
      version: ${{ needs.build.outputs.version }}
    needs: [build]
    secrets: inherit

  update-podspec:
    name: Update Podspec
    uses: ./.github/workflows/reusable/update-podspecs.yml
    with: 
      name: ${{ needs.publish.outputs.name }}
      version: ${{ needs.publish.outputs.version }}
    needs: [publish]
    secrets: inherit