# This workflow will build a Swift project

name: Swift

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest  # Usa uma máquina macOS

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Versão do Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Instalar Dependências do CocoaPods
        run: |
          gem install cocoapods
          pod install
        working-directory: ./Example # Mude caso seu Podfile esteja em outro lugar

      - name: Compilar e Criar .xcframework
        run: |
          xcodebuild archive -workspace ./Example/CarotaService.xcworkspace \
          -scheme CarotaService \
          -destination "generic/platform=iOS" \
          -archivePath build/ios.xcarchive \
          -sdk iphoneos \
          SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          IPHONEOS_DEPLOYMENT_TARGET=15.0

          xcodebuild archive -workspace ./Example/CarotaService.xcworkspace \
          -scheme CarotaService \
          -destination "generic/platform=iOS Simulator" \
          -archivePath build/ios-simulator.xcarchive \
          -sdk iphonesimulator \
          SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          IPHONEOS_DEPLOYMENT_TARGET=15.0

          xcodebuild -create-xcframework \
          -framework build/ios.xcarchive/Products/Library/Frameworks/CarotaService.framework \
          -framework build/ios-simulator.xcarchive/Products/Library/Frameworks/CarotaService.framework \
          -output build/CarotaService.xcframework

      - name: Compactar .xcframework
        run: |
          cd build
          zip -r CarotaService.zip CarotaService.xcframework

      - name: Instalar JFrog CLI
        run: curl -fL https://install-cli.jfrog.io | sh

      - name: Configurar JFrog CLI
        run: |
          jf c add meu-artifactory \
            --url=https://artifactory.carotaapp.com/artifactory \
            --user=${{ secrets.ARTIFACTORY_USER }} \
            --password=${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Upload com JFrog CLI
        run: |
          jf rt u "build/CarotaService.zip" "ios-repo/CarotaService/1.1.11/CarotaService.zip"