# This workflow will build a Swift project

name: Swift

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest  # Usa uma máquina macOS

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Versão do Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Instalar Dependências do CocoaPods
        run: |
          gem install cocoapods
          pod install
        working-directory: ./Example # Mude caso seu Podfile esteja em outro lugar

      - name: Compilar o Projeto
        run: |
          xcodebuild clean build \
          -workspace Example/CarotaService.xcworkspace \
          -scheme CarotaService \
          -sdk iphoneos \
          -archivePath build/CarotaService.xcarchive \
          CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Exportar o Build para .ipa
        run: |
          xcodebuild -exportArchive \
          -archivePath build/CarotaService.xcarchive \
          -exportPath build/output \
          -exportOptionsPlist exportOptions.plist

      - name: Upload para Artifactory
        env:
          ARTIFACTORY_URL: "http://artifactory.carotaapp.com/artifactory/ios-repo/"
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          curl -u "$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD" \
          -T build/output/CarotaService.ipa \
          "$ARTIFACTORY_URL/CarotaService.ipa"